# Connection url for the database "netgloo_blog"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      search:
        default:
          indexmanager: elasticsearch
          elasticsearch:
            host: http://127.0.0.1:9300
            index_schema_management_strategy: drop-and-create
        


